import { FormField } from './types'

// Florida Family Law Financial Affidavit Form Fields
// Based on Florida Family Law Rule 12.902(b) and 12.902(c)

export interface FloridaFinancialAffidavit {
  sections: {
    personalInfo: FormField[]
    income: FormField[]
    deductions: FormField[]
    expenses: FormField[]
    assets: FormField[]
    liabilities: FormField[]
  }
}

export const floridaFormFields: FloridaFinancialAffidavit = {
  sections: {
    personalInfo: [
      {
        id: 'full_name',
        label: 'Full Legal Name',
        value: '',
        type: 'text',
      },
      {
        id: 'address',
        label: 'Street Address',
        value: '',
        type: 'text',
      },
      {
        id: 'city_state_zip',
        label: 'City, State, ZIP',
        value: '',
        type: 'text',
      },
      {
        id: 'phone',
        label: 'Telephone Number',
        value: '',
        type: 'text',
      },
      {
        id: 'ssn',
        label: 'Social Security Number',
        value: '',
        type: 'text',
      },
      {
        id: 'occupation',
        label: 'Occupation',
        value: '',
        type: 'text',
      },
      {
        id: 'employer',
        label: 'Employer',
        value: '',
        type: 'text',
      },
    ],
    income: [
      {
        id: 'gross_salary',
        label: 'Gross Monthly Salary or Wages',
        value: '',
        type: 'number',
      },
      {
        id: 'bonuses',
        label: 'Bonuses, Commissions, Allowances, Overtime',
        value: '',
        type: 'number',
      },
      {
        id: 'business_income',
        label: 'Business Income from Self-Employment',
        value: '',
        type: 'number',
      },
      {
        id: 'disability_benefits',
        label: 'Disability Benefits',
        value: '',
        type: 'number',
      },
      {
        id: 'workers_comp',
        label: "Workers' Compensation",
        value: '',
        type: 'number',
      },
      {
        id: 'unemployment',
        label: 'Unemployment Compensation',
        value: '',
        type: 'number',
      },
      {
        id: 'pension_retirement',
        label: 'Pension, Retirement, or Annuity Payments',
        value: '',
        type: 'number',
      },
      {
        id: 'social_security',
        label: 'Social Security Benefits',
        value: '',
        type: 'number',
      },
      {
        id: 'spousal_support',
        label: 'Spousal Support from Previous Marriage',
        value: '',
        type: 'number',
      },
      {
        id: 'interest_dividends',
        label: 'Interest and Dividends',
        value: '',
        type: 'number',
      },
      {
        id: 'rental_income',
        label: 'Rental Income',
        value: '',
        type: 'number',
      },
      {
        id: 'other_income',
        label: 'Other Income (specify)',
        value: '',
        type: 'number',
      },
      {
        id: 'total_monthly_gross_income',
        label: 'TOTAL MONTHLY GROSS INCOME',
        value: '',
        type: 'number',
      },
    ],
    deductions: [
      {
        id: 'federal_income_tax',
        label: 'Federal Income Tax',
        value: '',
        type: 'number',
      },
      {
        id: 'state_income_tax',
        label: 'State Income Tax',
        value: '',
        type: 'number',
      },
      {
        id: 'fica_medicare',
        label: 'FICA/Medicare',
        value: '',
        type: 'number',
      },
      {
        id: 'mandatory_union_dues',
        label: 'Mandatory Union Dues',
        value: '',
        type: 'number',
      },
      {
        id: 'mandatory_retirement',
        label: 'Mandatory Retirement',
        value: '',
        type: 'number',
      },
      {
        id: 'health_insurance',
        label: 'Health Insurance',
        value: '',
        type: 'number',
      },
      {
        id: 'court_ordered_child_support',
        label: 'Court Ordered Child Support',
        value: '',
        type: 'number',
      },
      {
        id: 'total_deductions',
        label: 'TOTAL DEDUCTIONS',
        value: '',
        type: 'number',
      },
      {
        id: 'net_monthly_income',
        label: 'NET MONTHLY INCOME',
        value: '',
        type: 'number',
      },
    ],
    expenses: [
      {
        id: 'mortgage_rent',
        label: 'Mortgage or Rent',
        value: '',
        type: 'number',
      },
      {
        id: 'property_taxes',
        label: 'Property Taxes',
        value: '',
        type: 'number',
      },
      {
        id: 'property_insurance',
        label: 'Property Insurance',
        value: '',
        type: 'number',
      },
      {
        id: 'hoa_fees',
        label: 'Homeowners Association Fees',
        value: '',
        type: 'number',
      },
      {
        id: 'electricity',
        label: 'Electricity',
        value: '',
        type: 'number',
      },
      {
        id: 'water',
        label: 'Water',
        value: '',
        type: 'number',
      },
      {
        id: 'gas',
        label: 'Natural Gas',
        value: '',
        type: 'number',
      },
      {
        id: 'telephone',
        label: 'Telephone',
        value: '',
        type: 'number',
      },
      {
        id: 'cable_internet',
        label: 'Cable/Internet',
        value: '',
        type: 'number',
      },
      {
        id: 'groceries',
        label: 'Groceries',
        value: '',
        type: 'number',
      },
      {
        id: 'clothing',
        label: 'Clothing',
        value: '',
        type: 'number',
      },
      {
        id: 'medical_dental',
        label: 'Medical/Dental',
        value: '',
        type: 'number',
      },
      {
        id: 'auto_payment',
        label: 'Automobile Payment',
        value: '',
        type: 'number',
      },
      {
        id: 'auto_insurance',
        label: 'Automobile Insurance',
        value: '',
        type: 'number',
      },
      {
        id: 'auto_maintenance',
        label: 'Automobile Maintenance and Gas',
        value: '',
        type: 'number',
      },
      {
        id: 'life_insurance',
        label: 'Life Insurance',
        value: '',
        type: 'number',
      },
      {
        id: 'child_care',
        label: 'Child Care',
        value: '',
        type: 'number',
      },
      {
        id: 'child_education',
        label: 'Children\'s Education',
        value: '',
        type: 'number',
      },
      {
        id: 'entertainment',
        label: 'Entertainment/Dining',
        value: '',
        type: 'number',
      },
      {
        id: 'personal_grooming',
        label: 'Personal Grooming',
        value: '',
        type: 'number',
      },
      {
        id: 'gifts',
        label: 'Gifts/Charitable Contributions',
        value: '',
        type: 'number',
      },
      {
        id: 'other_expenses',
        label: 'Other Expenses (specify)',
        value: '',
        type: 'number',
      },
      {
        id: 'total_monthly_expenses',
        label: 'TOTAL MONTHLY EXPENSES',
        value: '',
        type: 'number',
      },
    ],
    assets: [
      {
        id: 'cash',
        label: 'Cash (on hand)',
        value: '',
        type: 'number',
      },
      {
        id: 'checking_accounts',
        label: 'Checking Accounts',
        value: '',
        type: 'number',
      },
      {
        id: 'savings_accounts',
        label: 'Savings Accounts',
        value: '',
        type: 'number',
      },
      {
        id: 'money_market',
        label: 'Money Market Accounts',
        value: '',
        type: 'number',
      },
      {
        id: 'certificates_deposit',
        label: 'Certificates of Deposit',
        value: '',
        type: 'number',
      },
      {
        id: 'stocks_bonds',
        label: 'Stocks, Bonds, Notes',
        value: '',
        type: 'number',
      },
      {
        id: 'retirement_accounts',
        label: 'Retirement Accounts (IRA, 401k, etc.)',
        value: '',
        type: 'number',
      },
      {
        id: 'life_insurance_cash_value',
        label: 'Life Insurance (Cash Surrender Value)',
        value: '',
        type: 'number',
      },
      {
        id: 'real_estate',
        label: 'Real Estate',
        value: '',
        type: 'number',
      },
      {
        id: 'automobiles',
        label: 'Automobiles',
        value: '',
        type: 'number',
      },
      {
        id: 'boats_vehicles',
        label: 'Boats, Trailers, Other Vehicles',
        value: '',
        type: 'number',
      },
      {
        id: 'furniture_household',
        label: 'Furniture & Household Items',
        value: '',
        type: 'number',
      },
      {
        id: 'jewelry',
        label: 'Jewelry',
        value: '',
        type: 'number',
      },
      {
        id: 'business_interests',
        label: 'Business Interests',
        value: '',
        type: 'number',
      },
      {
        id: 'other_assets',
        label: 'Other Assets (specify)',
        value: '',
        type: 'number',
      },
      {
        id: 'total_assets',
        label: 'TOTAL ASSETS',
        value: '',
        type: 'number',
      },
    ],
    liabilities: [
      {
        id: 'mortgages',
        label: 'Mortgages on Real Estate',
        value: '',
        type: 'number',
      },
      {
        id: 'auto_loans',
        label: 'Automobile Loans',
        value: '',
        type: 'number',
      },
      {
        id: 'credit_cards',
        label: 'Credit Card Debts',
        value: '',
        type: 'number',
      },
      {
        id: 'student_loans',
        label: 'Student Loans',
        value: '',
        type: 'number',
      },
      {
        id: 'personal_loans',
        label: 'Personal Loans',
        value: '',
        type: 'number',
      },
      {
        id: 'tax_liabilities',
        label: 'Taxes Owed',
        value: '',
        type: 'number',
      },
      {
        id: 'medical_bills',
        label: 'Medical Bills',
        value: '',
        type: 'number',
      },
      {
        id: 'other_debts',
        label: 'Other Debts (specify)',
        value: '',
        type: 'number',
      },
      {
        id: 'total_liabilities',
        label: 'TOTAL LIABILITIES',
        value: '',
        type: 'number',
      },
      {
        id: 'net_worth',
        label: 'NET WORTH (Total Assets - Total Liabilities)',
        value: '',
        type: 'number',
      },
    ],
  },
}

// Auto-population logic - simulated extraction from documents
export const autoPopulateFromDocuments = (): FloridaFinancialAffidavit => {
  return {
    sections: {
      personalInfo: [
        {
          id: 'full_name',
          label: 'Full Legal Name',
          value: 'John Michael Smith',
          type: 'text',
          source: {
            document: 'Tax Return 2023',
            page: 1,
            extracted: 'Name: John Michael Smith',
          },
        },
        {
          id: 'address',
          label: 'Street Address',
          value: '1234 Ocean Drive',
          type: 'text',
          source: {
            document: 'Bank Statement - Chase (January 2024)',
            page: 1,
            extracted: 'Mailing Address: 1234 Ocean Drive',
          },
        },
        {
          id: 'city_state_zip',
          label: 'City, State, ZIP',
          value: 'Miami, FL 33139',
          type: 'text',
          source: {
            document: 'Bank Statement - Chase (January 2024)',
            page: 1,
            extracted: 'Miami, FL 33139',
          },
        },
        {
          id: 'phone',
          label: 'Telephone Number',
          value: '(305) 555-0123',
          type: 'text',
        },
        {
          id: 'ssn',
          label: 'Social Security Number',
          value: '***-**-6789',
          type: 'text',
          source: {
            document: 'Tax Return 2023',
            page: 1,
            extracted: 'SSN: XXX-XX-6789',
          },
        },
        {
          id: 'occupation',
          label: 'Occupation',
          value: 'Software Engineer',
          type: 'text',
          source: {
            document: 'Pay Stub - March 2024',
            page: 1,
            extracted: 'Position: Software Engineer',
          },
        },
        {
          id: 'employer',
          label: 'Employer',
          value: 'Tech Solutions Inc.',
          type: 'text',
          source: {
            document: 'Pay Stub - March 2024',
            page: 1,
            extracted: 'Employer: Tech Solutions Inc.',
          },
        },
      ],
      income: [
        {
          id: 'gross_salary',
          label: 'Gross Monthly Salary or Wages',
          value: '8500.00',
          type: 'number',
          source: {
            document: 'Pay Stubs (March, April 2024)',
            extracted: 'Average Gross Pay: $8,500.00',
          },
        },
        {
          id: 'bonuses',
          label: 'Bonuses, Commissions, Allowances, Overtime',
          value: '500.00',
          type: 'number',
          source: {
            document: 'Pay Stub - April 2024',
            extracted: 'Overtime: $500.00',
          },
        },
        {
          id: 'business_income',
          label: 'Business Income from Self-Employment',
          value: '0',
          type: 'number',
        },
        {
          id: 'disability_benefits',
          label: 'Disability Benefits',
          value: '0',
          type: 'number',
        },
        {
          id: 'workers_comp',
          label: "Workers' Compensation",
          value: '0',
          type: 'number',
        },
        {
          id: 'unemployment',
          label: 'Unemployment Compensation',
          value: '0',
          type: 'number',
        },
        {
          id: 'pension_retirement',
          label: 'Pension, Retirement, or Annuity Payments',
          value: '0',
          type: 'number',
        },
        {
          id: 'social_security',
          label: 'Social Security Benefits',
          value: '0',
          type: 'number',
        },
        {
          id: 'spousal_support',
          label: 'Spousal Support from Previous Marriage',
          value: '0',
          type: 'number',
        },
        {
          id: 'interest_dividends',
          label: 'Interest and Dividends',
          value: '125.00',
          type: 'number',
          source: {
            document: 'Bank Statements (Jan-Mar 2024)',
            extracted: 'Average Monthly Interest: $125.00',
          },
        },
        {
          id: 'rental_income',
          label: 'Rental Income',
          value: '0',
          type: 'number',
        },
        {
          id: 'other_income',
          label: 'Other Income (specify)',
          value: '0',
          type: 'number',
        },
        {
          id: 'total_monthly_gross_income',
          label: 'TOTAL MONTHLY GROSS INCOME',
          value: '9125.00',
          type: 'number',
          source: {
            document: 'Calculated from pay stubs and bank statements',
            extracted: 'Total: $9,125.00',
          },
        },
      ],
      deductions: [
        {
          id: 'federal_income_tax',
          label: 'Federal Income Tax',
          value: '1450.00',
          type: 'number',
          source: {
            document: 'Pay Stub - March 2024',
            extracted: 'Federal Tax: $1,450.00',
          },
        },
        {
          id: 'state_income_tax',
          label: 'State Income Tax',
          value: '0',
          type: 'number',
          source: {
            document: 'Pay Stub - March 2024',
            extracted: 'State Tax: $0.00 (Florida has no state income tax)',
          },
        },
        {
          id: 'fica_medicare',
          label: 'FICA/Medicare',
          value: '650.00',
          type: 'number',
          source: {
            document: 'Pay Stub - March 2024',
            extracted: 'FICA/Medicare: $650.00',
          },
        },
        {
          id: 'mandatory_union_dues',
          label: 'Mandatory Union Dues',
          value: '0',
          type: 'number',
        },
        {
          id: 'mandatory_retirement',
          label: 'Mandatory Retirement',
          value: '425.00',
          type: 'number',
          source: {
            document: 'Pay Stub - March 2024',
            extracted: '401(k) Contribution: $425.00',
          },
        },
        {
          id: 'health_insurance',
          label: 'Health Insurance',
          value: '350.00',
          type: 'number',
          source: {
            document: 'Pay Stub - March 2024',
            extracted: 'Health Insurance: $350.00',
          },
        },
        {
          id: 'court_ordered_child_support',
          label: 'Court Ordered Child Support',
          value: '0',
          type: 'number',
        },
        {
          id: 'total_deductions',
          label: 'TOTAL DEDUCTIONS',
          value: '2875.00',
          type: 'number',
          source: {
            document: 'Calculated from pay stubs',
            extracted: 'Total Deductions: $2,875.00',
          },
        },
        {
          id: 'net_monthly_income',
          label: 'NET MONTHLY INCOME',
          value: '6250.00',
          type: 'number',
          source: {
            document: 'Calculated: Gross Income - Deductions',
            extracted: 'Net Monthly Income: $6,250.00',
          },
        },
      ],
      expenses: [
        {
          id: 'mortgage_rent',
          label: 'Mortgage or Rent',
          value: '2200.00',
          type: 'number',
          source: {
            document: 'Bank Statement - Chase (recurring payment)',
            extracted: 'Monthly Mortgage Payment: $2,200.00',
          },
        },
        {
          id: 'property_taxes',
          label: 'Property Taxes',
          value: '350.00',
          type: 'number',
        },
        {
          id: 'property_insurance',
          label: 'Property Insurance',
          value: '150.00',
          type: 'number',
        },
        {
          id: 'hoa_fees',
          label: 'Homeowners Association Fees',
          value: '125.00',
          type: 'number',
        },
        {
          id: 'electricity',
          label: 'Electricity',
          value: '180.00',
          type: 'number',
          source: {
            document: 'Bank Statement - average utility payments',
            extracted: 'FPL Electric Co: ~$180.00',
          },
        },
        {
          id: 'water',
          label: 'Water',
          value: '65.00',
          type: 'number',
        },
        {
          id: 'gas',
          label: 'Natural Gas',
          value: '40.00',
          type: 'number',
        },
        {
          id: 'telephone',
          label: 'Telephone',
          value: '85.00',
          type: 'number',
        },
        {
          id: 'cable_internet',
          label: 'Cable/Internet',
          value: '120.00',
          type: 'number',
        },
        {
          id: 'groceries',
          label: 'Groceries',
          value: '600.00',
          type: 'number',
          source: {
            document: 'Credit Card & Bank Statements',
            extracted: 'Average grocery spending: $600.00',
          },
        },
        {
          id: 'clothing',
          label: 'Clothing',
          value: '150.00',
          type: 'number',
        },
        {
          id: 'medical_dental',
          label: 'Medical/Dental',
          value: '200.00',
          type: 'number',
        },
        {
          id: 'auto_payment',
          label: 'Automobile Payment',
          value: '450.00',
          type: 'number',
          source: {
            document: 'Bank Statement - recurring auto loan payment',
            extracted: 'Honda Finance: $450.00',
          },
        },
        {
          id: 'auto_insurance',
          label: 'Automobile Insurance',
          value: '175.00',
          type: 'number',
        },
        {
          id: 'auto_maintenance',
          label: 'Automobile Maintenance and Gas',
          value: '250.00',
          type: 'number',
        },
        {
          id: 'life_insurance',
          label: 'Life Insurance',
          value: '75.00',
          type: 'number',
        },
        {
          id: 'child_care',
          label: 'Child Care',
          value: '0',
          type: 'number',
        },
        {
          id: 'child_education',
          label: 'Children\'s Education',
          value: '0',
          type: 'number',
        },
        {
          id: 'entertainment',
          label: 'Entertainment/Dining',
          value: '300.00',
          type: 'number',
        },
        {
          id: 'personal_grooming',
          label: 'Personal Grooming',
          value: '75.00',
          type: 'number',
        },
        {
          id: 'gifts',
          label: 'Gifts/Charitable Contributions',
          value: '100.00',
          type: 'number',
        },
        {
          id: 'other_expenses',
          label: 'Other Expenses (specify)',
          value: '150.00',
          type: 'number',
        },
        {
          id: 'total_monthly_expenses',
          label: 'TOTAL MONTHLY EXPENSES',
          value: '5840.00',
          type: 'number',
          source: {
            document: 'Calculated from bank and credit card statements',
            extracted: 'Total Monthly Expenses: $5,840.00',
          },
        },
      ],
      assets: [
        {
          id: 'cash',
          label: 'Cash (on hand)',
          value: '500.00',
          type: 'number',
        },
        {
          id: 'checking_accounts',
          label: 'Checking Accounts',
          value: '3200.00',
          type: 'number',
          source: {
            document: 'Chase Checking - February 2024 Statement',
            extracted: 'Ending Balance: $3,200.00',
          },
        },
        {
          id: 'savings_accounts',
          label: 'Savings Accounts',
          value: '12500.00',
          type: 'number',
          source: {
            document: 'HSBC Savings - January 2024 Statement',
            extracted: 'Balance: $12,500.00',
          },
        },
        {
          id: 'money_market',
          label: 'Money Market Accounts',
          value: '0',
          type: 'number',
        },
        {
          id: 'certificates_deposit',
          label: 'Certificates of Deposit',
          value: '0',
          type: 'number',
        },
        {
          id: 'stocks_bonds',
          label: 'Stocks, Bonds, Notes',
          value: '0',
          type: 'number',
        },
        {
          id: 'retirement_accounts',
          label: 'Retirement Accounts (IRA, 401k, etc.)',
          value: '45000.00',
          type: 'number',
          source: {
            document: 'Employment Benefits Statement',
            extracted: '401(k) Balance: $45,000.00',
          },
        },
        {
          id: 'life_insurance_cash_value',
          label: 'Life Insurance (Cash Surrender Value)',
          value: '2500.00',
          type: 'number',
        },
        {
          id: 'real_estate',
          label: 'Real Estate',
          value: '425000.00',
          type: 'number',
          source: {
            document: 'Property Deed - Miami House',
            extracted: 'Estimated Market Value: $425,000.00',
          },
        },
        {
          id: 'automobiles',
          label: 'Automobiles',
          value: '22000.00',
          type: 'number',
          source: {
            document: 'Vehicle Title',
            extracted: 'Estimated Value: $22,000.00',
          },
        },
        {
          id: 'boats_vehicles',
          label: 'Boats, Trailers, Other Vehicles',
          value: '0',
          type: 'number',
        },
        {
          id: 'furniture_household',
          label: 'Furniture & Household Items',
          value: '15000.00',
          type: 'number',
        },
        {
          id: 'jewelry',
          label: 'Jewelry',
          value: '3000.00',
          type: 'number',
        },
        {
          id: 'business_interests',
          label: 'Business Interests',
          value: '0',
          type: 'number',
        },
        {
          id: 'other_assets',
          label: 'Other Assets (specify)',
          value: '0',
          type: 'number',
        },
        {
          id: 'total_assets',
          label: 'TOTAL ASSETS',
          value: '528700.00',
          type: 'number',
          source: {
            document: 'Calculated from all asset documentation',
            extracted: 'Total Assets: $528,700.00',
          },
        },
      ],
      liabilities: [
        {
          id: 'mortgages',
          label: 'Mortgages on Real Estate',
          value: '285000.00',
          type: 'number',
          source: {
            document: 'Mortgage Statement',
            extracted: 'Principal Balance: $285,000.00',
          },
        },
        {
          id: 'auto_loans',
          label: 'Automobile Loans',
          value: '18500.00',
          type: 'number',
          source: {
            document: 'Auto Loan Statement',
            extracted: 'Remaining Balance: $18,500.00',
          },
        },
        {
          id: 'credit_cards',
          label: 'Credit Card Debts',
          value: '4200.00',
          type: 'number',
          source: {
            document: 'Credit Card Statements',
            extracted: 'Total Credit Card Balance: $4,200.00',
          },
        },
        {
          id: 'student_loans',
          label: 'Student Loans',
          value: '0',
          type: 'number',
        },
        {
          id: 'personal_loans',
          label: 'Personal Loans',
          value: '0',
          type: 'number',
        },
        {
          id: 'tax_liabilities',
          label: 'Taxes Owed',
          value: '0',
          type: 'number',
        },
        {
          id: 'medical_bills',
          label: 'Medical Bills',
          value: '0',
          type: 'number',
        },
        {
          id: 'other_debts',
          label: 'Other Debts (specify)',
          value: '0',
          type: 'number',
        },
        {
          id: 'total_liabilities',
          label: 'TOTAL LIABILITIES',
          value: '307700.00',
          type: 'number',
          source: {
            document: 'Calculated from all liability documentation',
            extracted: 'Total Liabilities: $307,700.00',
          },
        },
        {
          id: 'net_worth',
          label: 'NET WORTH (Total Assets - Total Liabilities)',
          value: '221000.00',
          type: 'number',
          source: {
            document: 'Calculated: Assets - Liabilities',
            extracted: 'Net Worth: $221,000.00',
          },
        },
      ],
    },
  }
}

// Mock Opposition Party Financial Affidavit
// This data represents the opposing party's claimed financial information
export function getOppositionFormData(oppositionName: string): FloridaFinancialAffidavit {
  return {
    sections: {
      personalInfo: [
        {
          id: 'full_name',
          label: 'Full Legal Name',
          value: oppositionName,
          type: 'text',
        },
        {
          id: 'address',
          label: 'Street Address',
          value: '456 Palm Avenue',
          type: 'text',
        },
        {
          id: 'city_state_zip',
          label: 'City, State, ZIP',
          value: 'Miami, FL 33139',
          type: 'text',
        },
        {
          id: 'phone',
          label: 'Telephone Number',
          value: '(305) 555-0199',
          type: 'text',
        },
        {
          id: 'ssn',
          label: 'Social Security Number',
          value: '***-**-5678',
          type: 'text',
        },
        {
          id: 'dob',
          label: 'Date of Birth',
          value: '1982-07-15',
          type: 'date',
        },
        {
          id: 'occupation',
          label: 'Occupation',
          value: 'Marketing Manager',
          type: 'text',
        },
      ],
      income: [
        {
          id: 'monthly_salary',
          label: 'Monthly Salary or Wages',
          value: '8500.00',
          type: 'number',
          source: {
            document: 'Pay Stubs - Opposition',
            page: 1,
            extracted: 'Gross Monthly Pay: $8,500.00',
          },
        },
        {
          id: 'bonuses',
          label: 'Bonuses, Commissions, Allowances',
          value: '500.00',
          type: 'number',
          source: {
            document: 'Pay Stubs - Opposition',
            page: 1,
            extracted: 'Monthly Bonus: $500.00',
          },
        },
        {
          id: 'business_income',
          label: 'Business Income',
          value: '0',
          type: 'number',
        },
        {
          id: 'disability_benefits',
          label: 'Disability Benefits',
          value: '0',
          type: 'number',
        },
        {
          id: 'workers_comp',
          label: 'Workers Compensation',
          value: '0',
          type: 'number',
        },
        {
          id: 'unemployment',
          label: 'Unemployment Compensation',
          value: '0',
          type: 'number',
        },
        {
          id: 'pension_retirement',
          label: 'Pension, Retirement, Annuities',
          value: '0',
          type: 'number',
        },
        {
          id: 'social_security',
          label: 'Social Security Benefits',
          value: '0',
          type: 'number',
        },
        {
          id: 'spousal_support',
          label: 'Spousal Support from Other',
          value: '0',
          type: 'number',
        },
        {
          id: 'rental_income',
          label: 'Rental Income',
          value: '0',
          type: 'number',
        },
        {
          id: 'investment_income',
          label: 'Interest and Dividends',
          value: '150.00',
          type: 'number',
          source: {
            document: 'Bank Statements - Opposition',
            page: 2,
            extracted: 'Monthly Interest Income: $150.00',
          },
        },
        {
          id: 'other_income',
          label: 'Other Income (specify)',
          value: '0',
          type: 'number',
        },
        {
          id: 'total_gross_income',
          label: 'TOTAL GROSS MONTHLY INCOME',
          value: '9150.00',
          type: 'number',
          source: {
            document: 'Calculated from all income sources',
            extracted: 'Total Monthly Income: $9,150.00',
          },
        },
      ],
      deductions: [
        {
          id: 'federal_tax',
          label: 'Federal Income Tax',
          value: '1350.00',
          type: 'number',
          source: {
            document: 'Pay Stubs - Opposition',
            page: 1,
            extracted: 'Federal Tax Withheld: $1,350.00',
          },
        },
        {
          id: 'state_tax',
          label: 'State Income Tax',
          value: '0',
          type: 'number',
        },
        {
          id: 'fica',
          label: 'FICA/Self-Employment Tax',
          value: '650.00',
          type: 'number',
          source: {
            document: 'Pay Stubs - Opposition',
            page: 1,
            extracted: 'FICA: $650.00',
          },
        },
        {
          id: 'medicare',
          label: 'Medicare Tax',
          value: '123.00',
          type: 'number',
          source: {
            document: 'Pay Stubs - Opposition',
            page: 1,
            extracted: 'Medicare: $123.00',
          },
        },
        {
          id: 'mandatory_union',
          label: 'Mandatory Union Dues',
          value: '0',
          type: 'number',
        },
        {
          id: 'mandatory_retirement',
          label: 'Mandatory Retirement',
          value: '425.00',
          type: 'number',
          source: {
            document: 'Pay Stubs - Opposition',
            page: 1,
            extracted: '401(k) Contribution: $425.00',
          },
        },
        {
          id: 'health_insurance',
          label: 'Health Insurance',
          value: '280.00',
          type: 'number',
          source: {
            document: 'Pay Stubs - Opposition',
            page: 1,
            extracted: 'Health Insurance: $280.00',
          },
        },
        {
          id: 'court_ordered_support',
          label: 'Court-Ordered Child/Spousal Support',
          value: '0',
          type: 'number',
        },
        {
          id: 'total_deductions',
          label: 'TOTAL DEDUCTIONS',
          value: '2828.00',
          type: 'number',
          source: {
            document: 'Calculated from pay stub deductions',
            extracted: 'Total Monthly Deductions: $2,828.00',
          },
        },
        {
          id: 'net_monthly_income',
          label: 'NET MONTHLY INCOME',
          value: '6322.00',
          type: 'number',
          source: {
            document: 'Pay Stubs - Opposition',
            page: 1,
            extracted: 'Net Monthly Pay: $6,322.00',
          },
        },
      ],
      expenses: [
        {
          id: 'mortgage_rent',
          label: 'Mortgage or Rent',
          value: '1900.00',
          type: 'number',
          source: {
            document: 'Lease Agreement - Opposition',
            page: 1,
            extracted: 'Monthly Rent: $1,900.00',
          },
        },
        {
          id: 'property_tax',
          label: 'Property Tax (if not in mortgage)',
          value: '0',
          type: 'number',
        },
        {
          id: 'electricity',
          label: 'Electricity',
          value: '130.00',
          type: 'number',
        },
        {
          id: 'water_sewer',
          label: 'Water, Sewer, Trash',
          value: '65.00',
          type: 'number',
        },
        {
          id: 'telephone',
          label: 'Telephone',
          value: '85.00',
          type: 'number',
        },
        {
          id: 'cable_internet',
          label: 'Cable, Internet',
          value: '110.00',
          type: 'number',
        },
        {
          id: 'groceries',
          label: 'Groceries',
          value: '550.00',
          type: 'number',
        },
        {
          id: 'meals_outside',
          label: 'Meals Outside Home',
          value: '300.00',
          type: 'number',
        },
        {
          id: 'auto_payment',
          label: 'Automobile Payments',
          value: '420.00',
          type: 'number',
          source: {
            document: 'Auto Loan Statement - Opposition',
            page: 1,
            extracted: 'Monthly Payment: $420.00',
          },
        },
        {
          id: 'auto_insurance',
          label: 'Automobile Insurance',
          value: '165.00',
          type: 'number',
        },
        {
          id: 'gas_oil',
          label: 'Gasoline, Oil',
          value: '200.00',
          type: 'number',
        },
        {
          id: 'auto_maintenance',
          label: 'Automobile Maintenance',
          value: '100.00',
          type: 'number',
        },
        {
          id: 'life_insurance',
          label: 'Life Insurance',
          value: '75.00',
          type: 'number',
        },
        {
          id: 'medical_dental',
          label: 'Medical, Dental (not reimbursed)',
          value: '150.00',
          type: 'number',
        },
        {
          id: 'prescriptions',
          label: 'Prescriptions (not reimbursed)',
          value: '45.00',
          type: 'number',
        },
        {
          id: 'clothing',
          label: 'Clothing',
          value: '180.00',
          type: 'number',
        },
        {
          id: 'dry_cleaning',
          label: 'Dry Cleaning, Laundry',
          value: '40.00',
          type: 'number',
        },
        {
          id: 'entertainment',
          label: 'Entertainment, Gifts',
          value: '220.00',
          type: 'number',
        },
        {
          id: 'pet_care',
          label: 'Pet Care',
          value: '80.00',
          type: 'number',
        },
        {
          id: 'memberships',
          label: 'Memberships, Subscriptions',
          value: '95.00',
          type: 'number',
        },
        {
          id: 'personal_care',
          label: 'Barber, Beauty, Personal Care',
          value: '120.00',
          type: 'number',
        },
        {
          id: 'child_care',
          label: 'Child Care',
          value: '0',
          type: 'number',
        },
        {
          id: 'child_education',
          label: "Children's Education",
          value: '0',
          type: 'number',
        },
        {
          id: 'other_expenses',
          label: 'Other (specify)',
          value: '150.00',
          type: 'number',
        },
        {
          id: 'total_expenses',
          label: 'TOTAL MONTHLY EXPENSES',
          value: '5375.00',
          type: 'number',
          source: {
            document: 'Calculated from all expense receipts',
            extracted: 'Total Monthly Expenses: $5,375.00',
          },
        },
      ],
      assets: [
        {
          id: 'cash_accounts',
          label: 'Cash (on hand)',
          value: '1200.00',
          type: 'number',
        },
        {
          id: 'checking_accounts',
          label: 'Checking Accounts',
          value: '8500.00',
          type: 'number',
          source: {
            document: 'Bank Statement - Wells Fargo Checking',
            page: 1,
            extracted: 'Current Balance: $8,500.00',
          },
        },
        {
          id: 'savings_accounts',
          label: 'Savings Accounts',
          value: '18000.00',
          type: 'number',
          source: {
            document: 'Bank Statement - Wells Fargo Savings',
            page: 1,
            extracted: 'Current Balance: $18,000.00',
          },
        },
        {
          id: 'money_market',
          label: 'Money Market Accounts',
          value: '5000.00',
          type: 'number',
          source: {
            document: 'Bank Statement - Money Market Account',
            page: 1,
            extracted: 'Current Balance: $5,000.00',
          },
        },
        {
          id: 'certificates_deposit',
          label: 'Certificates of Deposit',
          value: '0',
          type: 'number',
        },
        {
          id: 'stocks_bonds',
          label: 'Stocks, Bonds, Notes',
          value: '12000.00',
          type: 'number',
          source: {
            document: 'Investment Account Statement',
            page: 1,
            extracted: 'Portfolio Value: $12,000.00',
          },
        },
        {
          id: 'retirement_accounts',
          label: 'Retirement Accounts (401k, IRA, etc.)',
          value: '67000.00',
          type: 'number',
          source: {
            document: '401(k) Account Statement - Opposition',
            page: 1,
            extracted: 'Account Balance: $67,000.00',
          },
        },
        {
          id: 'real_estate',
          label: 'Real Estate (home, other property)',
          value: '0',
          type: 'number',
        },
        {
          id: 'automobiles',
          label: 'Automobiles',
          value: '24000.00',
          type: 'number',
          source: {
            document: 'Vehicle Appraisal - 2020 Honda Accord',
            page: 1,
            extracted: 'Estimated Value: $24,000.00',
          },
        },
        {
          id: 'boats_vehicles',
          label: 'Boats, Trailers, Other Vehicles',
          value: '0',
          type: 'number',
        },
        {
          id: 'furniture_household',
          label: 'Furniture & Household Items',
          value: '8000.00',
          type: 'number',
        },
        {
          id: 'jewelry',
          label: 'Jewelry',
          value: '2500.00',
          type: 'number',
        },
        {
          id: 'business_interests',
          label: 'Business Interests',
          value: '0',
          type: 'number',
        },
        {
          id: 'other_assets',
          label: 'Other Assets (specify)',
          value: '0',
          type: 'number',
        },
        {
          id: 'total_assets',
          label: 'TOTAL ASSETS',
          value: '146200.00',
          type: 'number',
          source: {
            document: 'Calculated from all asset documentation',
            extracted: 'Total Assets: $146,200.00',
          },
        },
      ],
      liabilities: [
        {
          id: 'mortgages',
          label: 'Mortgages on Real Estate',
          value: '0',
          type: 'number',
        },
        {
          id: 'auto_loans',
          label: 'Automobile Loans',
          value: '15500.00',
          type: 'number',
          source: {
            document: 'Auto Loan Statement - Opposition',
            page: 1,
            extracted: 'Principal Balance: $15,500.00',
          },
        },
        {
          id: 'credit_cards',
          label: 'Credit Card Debts',
          value: '8200.00',
          type: 'number',
          source: {
            document: 'Credit Card Statements - Opposition',
            page: 1,
            extracted: 'Total Credit Card Balance: $8,200.00',
          },
        },
        {
          id: 'student_loans',
          label: 'Student Loans',
          value: '18000.00',
          type: 'number',
          source: {
            document: 'Student Loan Statement',
            page: 1,
            extracted: 'Outstanding Balance: $18,000.00',
          },
        },
        {
          id: 'personal_loans',
          label: 'Personal Loans',
          value: '0',
          type: 'number',
        },
        {
          id: 'tax_liabilities',
          label: 'Taxes Owed',
          value: '0',
          type: 'number',
        },
        {
          id: 'medical_bills',
          label: 'Medical Bills',
          value: '1200.00',
          type: 'number',
        },
        {
          id: 'other_debts',
          label: 'Other Debts (specify)',
          value: '0',
          type: 'number',
        },
        {
          id: 'total_liabilities',
          label: 'TOTAL LIABILITIES',
          value: '42900.00',
          type: 'number',
          source: {
            document: 'Calculated from all liability documentation',
            extracted: 'Total Liabilities: $42,900.00',
          },
        },
        {
          id: 'net_worth',
          label: 'NET WORTH (Total Assets - Total Liabilities)',
          value: '103300.00',
          type: 'number',
          source: {
            document: 'Calculated: Assets - Liabilities',
            extracted: 'Net Worth: $103,300.00',
          },
        },
      ],
    },
  }
}

